In [1]:
import numpy as np

I want to model the weather. I'll assume that the Markov property applies here, even though that's probably not a very good assumption for us to make.

Let $C$ indicate **clear**, $R$ indicate **rainy**, and $S$ indicate **snowy**.

- If $X_i=C$, then $\mathbb{P}(X_{i+1}=C)=0.6$, $\mathbb{P}(X_{i+1}=R)=0.3$, $\mathbb{P}(X_{i+1}=S)=0.1$.
- If $X_i=R$, then $\mathbb{P}(X_{i+1}=C)=0.4$, $\mathbb{P}(X_{i+1}=R)=0.4$, $\mathbb{P}(X_{i+1}=S)=0.2$.
- If $X_i=S$, then $\mathbb{P}(X_{i+1}=C)=0.3$, $\mathbb{P}(X_{i+1}=R)=0.3$, $\mathbb{P}(X_{i+1}=S)=0.4$.

We can represent this in a matrix.

$$\begin{equation} \mathbf{A} = 
\left[\begin{array}{ccc} 
      0.6 & 0.4 & 0.3\\
      0.3 & 0.4 & 0.3\\
      0.1 & 0.2 & 0.4\\
\end{array}\right]
\end{equation}$$

The first row and first column represent clear, the second row and column represent rainy, and the third row and column represent snowy.

In [2]:
transition_matrix = np.array([[0.6, 0.4, 0.3],
                              [0.3, 0.4, 0.3],
                              [0.1, 0.2, 0.4]])

In [3]:
transition_matrix

array([[0.6, 0.4, 0.3],
       [0.3, 0.4, 0.3],
       [0.1, 0.2, 0.4]])

In order to find what the weather is like on day two ($\mathbf{y}_2$), I need to specify the weather on day 1 ($\mathbf{y}_1$), then multiply $\mathbf{A}$ by $\mathbf{y}_1$.

In [4]:
y_1 = np.array([0, 0, 1]) # Order is [C, R, S]

In [5]:
y_1

array([0, 0, 1])

In [6]:
y_2 = np.matmul(transition_matrix, y_1)

In [7]:
y_2

array([0.3, 0.3, 0.4])

In order to find what the weather is like on day three ($\mathbf{y}_3$), I need to specify the weather on day 2 ($\mathbf{y}_2$), then multiply $\mathbf{A}$ by $\mathbf{y}_2$.

In [8]:
y_3 = np.matmul(transition_matrix, y_2)

In [9]:
y_3

array([0.42, 0.33, 0.25])

We can actually find out the weather on day 3 from just using day 1!

$$
\begin{eqnarray*}
\mathbf{y}_3 &=& \mathbf{A}\mathbf{y}_2 \\
\mathbf{y}_3 &=& \mathbf{A}(\mathbf{A}\mathbf{y}_1) \\
\mathbf{y}_3 &=& \mathbf{A}^2\mathbf{y}_1 \\
\end{eqnarray*}
$$

In [10]:
np.matmul(np.matmul(transition_matrix,
                    transition_matrix), y_1)

array([0.42, 0.33, 0.25])

**What happens if we want to predict 1,000 days from now?**

In [11]:
def long_run(A, num_steps, first_state):
    A_power = np.linalg.matrix_power(A, num_steps)
    return np.matmul(A_power, first_state)

In [12]:
long_run(transition_matrix, 1000, y_1)

array([0.47619048, 0.33333333, 0.19047619])

**What about 10,000?**

In [13]:
long_run(transition_matrix, 10000, y_1)

array([0.47619048, 0.33333333, 0.19047619])

**Note:** Markov chains, under pretty weak assumptions, will converge to some long-run behavior. (This is really good for MCMC.)

**What happens if it's not snowy on day 1? How does this affect that long-run behavior?**

In [14]:
y_1 = np.array([0.5, 0.5, 0])

In [15]:
long_run(transition_matrix, 1000, y_1)

array([0.47619048, 0.33333333, 0.19047619])

**Note:** Markov chains, under pretty weak assumptions, will converge to some long-run behavior **independent of the starting point!** (This is *exceptionally* good for MCMC.)

**In this case, starting point does NOT mean prior. Starting point means the point where we start our random Monte Carlo sampling.**